---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
commonLabels:
  app: "mafiasi-dashboard"
resources:
  - "./k8s/deployment.yml"
  - "./k8s/services.yml"
configMapGenerator:
  - name: "mafiasi-dashboard"
