---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
commonLabels:
  app: "mafiasi-dashboard"
resources:
  - "./deployment.yml"
  - "./services.yml"
configMapGenerator:
  - name: "mafiasi-dashboard"
